all:
  csBackup:
    rsync:
      options:
        verbose:          true
        progress:         true
        stats:            true
        compress:         true
        rsh:              ssh
        recursive:        true
        times:            true
        perms:            true
        links:            true
        delete:           true
        exclude:          ['*.svn', '*.git']
      
      source:             [web/uploads]
    
      target:             false
      
    mysql:
      # Can be array of DB names
      # dbname:             [db1, db2]

      # email:              your@email.com
            
      backup_dir:         data/sql/backup
      
      command:            mysqldump
    
    scp:
      target:             false  # false for local machine

      target_dir:         ~/
      
      source:             [web/uploads]